### ISSUE TITLE
set-up-Kanban-board

### ISSUE THREAD

**Issue by Nelitaa** [Nelitaa/Capstone-Project-JavaScript#81]
https://github.com/users/Nelitaa/projects/5/views/1
In our group we are two persons.

**Comment by Gopxfs** [comment]
# 🟢 STATUS: APPROVED 🟢

## Hello team👋,

Your project is complete! You followed all the requirements, feel free to merge it! 😄
Congratulations! 🎉 

<img src="https://media.giphy.com/media/cXblnKXr2BQOaYnTni/giphy.gif">

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
